### PR TITLE
fix: shutdown ImageLoader onDropViewInstance on android

### LINKED ISSUE #309: Dynamic tabBarIcon stops working on Android when opening a modal if tab hasn't been previously focused
### Before submitting a new issue

- [x] I tested using the latest version of the library, as the bug might be already fixed.
- [x] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [x] I checked for possible duplicate issues, with possible answers.

### Bug summary

Once again, thank you for an awesome library! Really appreciate the work you put in and its amazing how fast you respond and fixes issues.

Seems like #304 didn't fix #298 completely because tabs do not change their icon based on `focused` after opening a modal if the tab has not previously been focused.

https://github.com/user-attachments/assets/20251db2-25c7-45bd-becb-39986bcb407d

### Library version

3.8.7

### Environment info

```shell
System:
  OS: macOS 15.3.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 260.52 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: ~/.nvm/versions/node/v20.17.0/bin/node
  Yarn:
    version: 4.6.0
    path: ~/.nvm/versions/node/v20.17.0/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.17.0/bin/npm
  Watchman:
    version: 2024.12.02.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/johan.kasperi/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK:
    API Levels:
      - "28"
      - "30"
      - "34"
      - "35"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 33.0.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
      - 34.0.0
      - 35.0.0
    System Images:
      - android-22 | Google APIs ARM 64 v8a
      - android-23 | Google APIs ARM 64 v8a
      - android-25 | Google APIs ARM 64 v8a
      - android-28 | Google ARM64-V8a Play ARM 64 v8a
      - android-35 | Google APIs ARM 64 v8a
      - android-VanillaIceCream | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12483815
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.5
    path: /Users/johan.kasperi/.sdkman/candidates/java/current/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/johan.kasperi/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: true
iOS:
  hermesEnabled: false
  newArchEnabled: false
```

### Steps to reproduce

1. Clone https://github.com/johankasperi/react-native-bottom-tabs/tree/android-modal-tabbaricon-bug
2. Run example app on Android
3. Open "Embedded stacks"

### Reproducible sample code

```js
https://github.com/johankasperi/react-native-bottom-tabs/tree/android-modal-tabbaricon-bug
```

### PR DESCRIPTION
**Pull request by johankasperi**
## PR Description

`imageLoader.shutdown()` is called `onDetachedFromWindow`. But this lifecycle method is called when opening a modal on top of the current view containing bottom tabs. When then closing the modal the `ImageLoader` has been shutdown and wont load icons anymore. Solved this by checking if `imageLoader` is null in the `getDrawable` method and if so creates it again.

Fixes #309 

## How to test?

1. Download fork at https://github.com/johankasperi/react-native-bottom-tabs/tree/android-modal-tabbaricon-bug
2. Run example app on Android
3. Open "Embedded Stacks" example
4. Open the modal and close it again
5. Change between the tabs and see that the icon changes when they are focused

### CODE REVIEW

File: packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt [hunk 1]
```diff
@@ -458,6 +462,7 @@ class ReactBottomNavigationView(context: Context) : LinearLayout(context) {
 
   override fun onDetachedFromWindow() {
     super.onDetachedFromWindow()
-    imageLoader.shutdown()
+    imageLoader?.shutdown()
+    imageLoader = null
```
Comment (okwasniewski) [inline packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt:466]: Ah! So `onDetachedFromWindow` was called when we opened the modal? I'm thinking whether this is a correct place to shut it down then... 


Maybe we should move the shutdown code somewhere else? Like into an LifecycleObserver: https://developer.android.com/reference/androidx/lifecycle/LifecycleObserver

**Review by okwasniewski — COMMENTED** [review]
Thanks for looking into this!

File: packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt (hunk 1 above)
Comment (johankasperi) [reply packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt:466]: Yeah `onDetachedFromWindow` was called when the modal was opened.

Yep my initial thought was to shutdown the `ImageLoader` somewhere else in the view lifecycle. But my knowledge about Android is limited and I couldn't find a more proper lifecycle method.

LifeCycleObserver looks interesting! But I can't find any example on how to implement it on a View. Can you point me in any direction?

Comment (johankasperi) [reply packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt:466]: tried this code in `init` but doesn't seem to work
```kotlin
    if (context is LifecycleOwner) {
      context.lifecycle.addObserver(object : DefaultLifecycleObserver {
        override fun onDestroy(owner: LifecycleOwner) {
          imageLoader.shutdown()
        }
      })
    }
```

Comment (okwasniewski) [reply packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt:466]: @johankasperi Looks like we could implement `onDropViewInstance` from React Native in the ViewManager class: 

https://github.com/facebook/react-native/blob/38190f530ffebd99ae3f70f86bda9e18f15b80e7/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/modal/ReactModalHostManager.kt#L35

We could deinitialize imageLoader there

Comment (johankasperi) [reply packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt:466]: Yeah thats right! Forgot about that one. Will give it a go asap

Comment (johankasperi) [reply packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt]: Implemented it now with `onDropViewInstance` instead

File: packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt [hunk 2]
```diff
@@ -384,6 +384,10 @@ class ReactBottomNavigationView(context: Context) : LinearLayout(context) {
     updateTextAppearance()
   }
 
+  fun shutdownImageLoader() {
```
Comment (okwasniewski) [inline packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt:387]: nit: Can we call this `onDropViewInstance`? If in the future there is some other deinit code then we will have universal function to do so.

File: packages/react-native-bottom-tabs/android/src/newarch/RCTTabViewManager.kt [hunk 3]
```diff
@@ -43,6 +43,11 @@ class RCTTabViewManager(context: ReactApplicationContext) :
 
   }
 
+  override fun onDropViewInstance(view: ReactBottomNavigationView) {
```
Comment (okwasniewski) [inline packages/react-native-bottom-tabs/android/src/newarch/RCTTabViewManager.kt:46]: We also need this function in `src/oldarch/RCTTabViewManager.kt`

**Review by okwasniewski — COMMENTED** [review]
Thanks for changing it! One more small nit and we are good to go

File: packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt (hunk 2 above)
Comment (johankasperi) [reply packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt:387]: Of course! Will fix asap

File: packages/react-native-bottom-tabs/android/src/newarch/RCTTabViewManager.kt (hunk 3 above)
Comment (johankasperi) [reply packages/react-native-bottom-tabs/android/src/newarch/RCTTabViewManager.kt:46]: Oh yeah you are right. Forgot about that. Will fix

**Review by okwasniewski — APPROVED** [review]
Thanks for fixing this!
